### ISSUE TITLE
Likely an import error?

### ISSUE THREAD

**Issue by Cole128** [reiinakano/scikit-plot#1]
When trying to install scikit-plot with pip3 I got this error:
```
Collecting scikit-plot
  Downloading scikit-plot-0.1.dev3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9g/pv05gc7d5zvb2n_pr_0tmn8r0000gn/T/pip-build-6c8p8iqs/scikit-plot/setup.py", line 9, in <module>
        import scikitplot
      File "/private/var/folders/9g/pv05gc7d5zvb2n_pr_0tmn8r0000gn/T/pip-build-6c8p8iqs/scikit-plot/scikitplot/__init__.py", line 5, in <module>
        from scikitplot.classifiers import classifier_factory
      File "/private/var/folders/9g/pv05gc7d5zvb2n_pr_0tmn8r0000gn/T/pip-build-6c8p8iqs/scikit-plot/scikitplot/classifiers.py", line 9, in <module>
        from sklearn.model_selection import learning_curve
    ModuleNotFoundError: No module named 'sklearn'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9g/pv05gc7d5zvb2n_pr_0tmn8r0000gn/T/pip-build-6c8p8iqs/scikit-plot/
```

My guess is just that classifiers.py just doesn't import sklearn.

**Comment by reiinakano** [comment]
Hi Cole, that's weird. I've tested it on a clean install of python 3 and installation works just fine so long as the dependencies (scikit-learn, matplotlib) are resolved. Are you sure scikit-learn>=0.18 is installed on the system?

Also, please note that I haven't had an official release yet and there's likely to be a handful of bugs in the package. Thanks a lot for taking the time to try out the pre-release version of the scikit-plot! :)

**Comment by Cole128** [comment]
Sorry, you're right. I thought I had scikit-learn installed but I didn't. Thanks!

**Comment by reiinakano** [comment]
No problem, glad you resolved it!
