### ISSUE TITLE
Bug: Failing to import Scikitplot fails due to ImportError

### ISSUE THREAD

**Issue by radlfabs** [reiinakano/scikit-plot#119]
Hey @reiinakano,

first, your work was a great addition to the open-source ML community and is still used. 👍 
Unfortunately, importing a freshly installed scikit-plot now fails with the following ImportErrror: 

```
import scikitplot
print("Hello World")
```

>>> import scikitplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\test-scikitplot\skplot\Lib\site-packages\scikitplot\__init__.py", line 2, in <module>
    from . import metrics, cluster, decomposition, estimators
  File "D:\test-scikitplot\skplot\Lib\site-packages\scikitplot\metrics.py", line 27, in <module>
    from scipy import interp
ImportError: cannot import name 'interp' from 'scipy' (D:\test-scikitplot\skplot\Lib\site-packages\scipy\__init__.py)

So what fails is https://github.com/reiinakano/scikit-plot/blob/2dd3e6a76df77edcbd724c4db25575f70abb57cb/scikitplot/metrics.py#L27

The interp-function can be imported from numpy instead.
This bug is severe, because it affects all packages trying to import scikit-plot at the moment.
I would highly appreciate you looking into this! Thanks a lot and best wishes!

**Comment by akosmaroy** [comment]
is there a workaround for this in the meantime?

**Comment by pplonski** [comment]
Please install `scipy==1.11.4` to fix this issue.

**Comment by linviaz** [comment]
A bit late in the conversation, but I created a pull request here to fix the issue: https://github.com/reiinakano/scikit-plot/pull/120

**Comment by pplonski** [comment]
I created a fork with @linviaz PR, I will maintain it https://github.com/mljar/mljar-scikit-plot

**Comment by laurendelong21** [comment]
> I created a fork with [@linviaz](https://github.com/linviaz) PR, I will maintain it https://github.com/mljar/mljar-scikit-plot

Came here with the same issue and this fork worked for me, thanks for making it!
